override['datadog']['api_key'] = '8cfd4c841751c518f433a199669cdd96'
override['datadog']['application_key'] = "6f0db093c5baf09c0e66a87ca4e3c547ba08caca"
override['chef-server']['base_dn'] = "cn=users,dc=vagrant,dc=atomia,dc=com"
override['chef-server']['bind_dn'] = "cn=bind,cn=users,dc=vagrant,dc=atomia,dc=com"
override['chef-server']['bind_password'] = 'Vagrant1'
override['chef-server']['group_dn'] = "cn=chef,cn=users,dc=vagrant,dc=atomia,dc=com"
override['chef-server']['host'] = '172.16.1.50'
override['chef-server']['port'] = '389'
override['chef-server']['login_attribute'] = 'sAMAccountName'